[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.pdo", "php82Extensions.pdo_mysql"]

[phases.install]
cmds = ["mkdir -p /app/public && cp -r ayamkings_backend/* /app/public/"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t /app/public"
